#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException
import ServiceClassifyInterface.ServiceClassifyInterface
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Iface(ServiceClassifyInterface.ServiceClassifyInterface.Iface):
  pass

class Client(ServiceClassifyInterface.ServiceClassifyInterface.Client, Iface):
  def __init__(self, iprot, oprot=None):
    ServiceClassifyInterface.ServiceClassifyInterface.Client.__init__(self, iprot, oprot)


class Processor(ServiceClassifyInterface.ServiceClassifyInterface.Processor, Iface, TProcessor):
  def __init__(self, handler):
    ServiceClassifyInterface.ServiceClassifyInterface.Processor.__init__(self, handler)

  def process(self, iprot, oprot):
    (name, type, seqid) = iprot.readMessageBegin()
    if name not in self._processMap:
      iprot.skip(TType.STRUCT)
      iprot.readMessageEnd()
      x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
      oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x.write(oprot)
      oprot.writeMessageEnd()
      oprot.trans.flush()
      return
    else:
      self._processMap[name](self, seqid, iprot, oprot)
    return True


# HELPER FUNCTIONS AND STRUCTURES
