apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: experiment-1
  labels:
    app: experiment-1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: experiment-1
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: Default
      nodeSelector:
        node: qktest 
      containers:
        - name: experiment-1
          image: registry.intra.weibo.com/weibo_rd_algorithmplatform/modelservice_lr:v1.1
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          ports:
            - containerPort: 17090
          env:
          - name: ENV_SERVICE_NAME
            value: "experiment_1"
          - name: ENV_SERVICE_PORT
            value: "17090"
          - name: ENV_MODEL_VERSION 
            value: "20180516115741"
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /data1/work/datasys/framework/service/workspace/plugin/experiment_1
              name: service
            - mountPath: /data1/work/datasys/framework/service/workspace/log
              name: log
            - mountPath: /data1/work/datasys/framework/service/monitor/log
              name: monitor
            - mountPath: /watch/log
              name: watch
            - mountPath: /corefile
              name: corefile
            - mountPath: /data1/work/datasys/framework/service/workspace/temp
              name: temp
            - mountPath: /data1/work/datasys/framework/service/workspace/bin/etc
              name: etc
      volumes:
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath:
            path: /data1/service/17090/experiment_1
          name: service
        - hostPath:
            path: /data1/service/17090/log
          name: log
        - hostPath:
            path: /data1/service/17090/log/monitor
          name: monitor
        - hostPath:
            path: /data1/service/17090/log/watch
          name: watch
        - hostPath:
            path: /data1/service/17090/log/corefile
          name: corefile
        - hostPath:
            path: /data1/service/17090/temp
          name: temp
        - hostPath:
            path: /data1/service/17090/etc
          name: etc
