#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException
from ttypes import *

MYSERVICEVALUETYPEARRAY = 0
MYSERVICEVALUETYPEJSON = 1
MYSERVICEVALUETYPEDICT = 2
MYSERVICEVALUETYPEVALUE = 3
